#!/bin/bash
set -e

export PATH=/usr/local/bin:$PATH
export APP_BUNDLE_PATH=`pwd`/testbbd/Frank/frankified_build/Frankified.app

eval "$(rbenv init -)"
rbenv local 2.1.1

bundle install

xcodebuild -scheme 'testbbd' -workspace test_frank_workspace.xcworkspace -sdk iphonesimulator8.1 clean test

cd testbbd

if [ ! -d Frank ]
then
  echo 1 | bundle exec frank setup
fi

bundle exec frank build --workspace ../test_frank_workspace.xcworkspace --scheme 'testbbd'
cd ..
bundle exec cucumber features